name: restaurants
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  http: 1.2.1
  shared_preferences: ^2.0.0
  path_provider: ^2.0.0
  latlong2: ^0.9.1
  flutter_map: ^6.1.0
  rxdart: ^0.27.7
  geolocator: ^12.0.0
  flutter_bloc: ^8.1.5
  geocoding: ^3.0.0


flutter:
  uses-material-design: true
